// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://dwzevlymqzpstliaxxgo.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR3emV2bHltcXpwc3RsaWF4eGdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzMwNTEzMDMsImV4cCI6MjA0ODYyNzMwM30.jAhraMTzkjsgEAIhZNTVdOsGMbPQC3WSYF3IvSGIxpQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);